language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash now-deploy.sh
  on:
    branch: master
#   github-token: $GH_TOKEN
#   keep-history: true
#   local-dir: build/
#   on:
#     branch: master
