language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn run build
# THIS DEPLOY FROM TRAVIS CI DOCS DOES NOT WORK.
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   local-dir: build/
#   on:
#     branch: master
